//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitedWomenMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UWSEntities : DbContext
    {
        public UWSEntities()
            : base("name=UWSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<United_Women_Sacco_Ltd_Members_Register> United_Women_Sacco_Ltd_Members_Register { get; set; }
        public virtual DbSet<UserActivation> UserActivations { get; set; }
        public virtual DbSet<United_Women_Sacco_Ltd_Loans_Register> United_Women_Sacco_Ltd_Loans_Register { get; set; }
        public virtual DbSet<United_Women_Sacco_Ltd_Member_Account_Signatories> United_Women_Sacco_Ltd_Member_Account_Signatories { get; set; }
        public virtual DbSet<United_Women_Sacco_Ltd_Member_App_Nominee> United_Women_Sacco_Ltd_Member_App_Nominee { get; set; }
        public virtual DbSet<United_Women_Sacco_Ltd_Member_Ledger_Entry> United_Women_Sacco_Ltd_Member_Ledger_Entry { get; set; }
        public virtual DbSet<United_Women_Sacco_Ltd_Members_Nominee> United_Women_Sacco_Ltd_Members_Nominee { get; set; }
        public virtual DbSet<United_Women_Sacco_Ltd_Vendor> United_Women_Sacco_Ltd_Vendor { get; set; }
    
        public virtual ObjectResult<string> Validate_User(string memberNo, string password)
        {
            var memberNoParameter = memberNo != null ?
                new ObjectParameter("MemberNo", memberNo) :
                new ObjectParameter("MemberNo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Validate_User", memberNoParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> ValidateUser(string memberNo, string password)
        {
            var memberNoParameter = memberNo != null ?
                new ObjectParameter("MemberNo", memberNo) :
                new ObjectParameter("MemberNo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ValidateUser", memberNoParameter, passwordParameter);
        }
    }
}
