namespace UnitedWomenMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class United_Women_Sacco_Ltd_Loans_Register
    {
        public byte[] timestamp { get; set; }
        public string Loan__No_ { get; set; }
        public System.DateTime Application_Date { get; set; }
        public string Loan_Product_Type { get; set; }
        public string Client_Code { get; set; }
        public string Group_Code { get; set; }
        public decimal Savings { get; set; }
        public decimal Existing_Loan { get; set; }
        public decimal Requested_Amount { get; set; }
        public decimal Approved_Amount { get; set; }
        public decimal Interest { get; set; }
        public decimal Insurance { get; set; }
        public string Source_of_Funds { get; set; }
        public int Client_Cycle { get; set; }
        public string Client_Name { get; set; }
        public int Loan_Status { get; set; }
        public System.DateTime Issued_Date { get; set; }
        public int Installments { get; set; }
        public System.DateTime Loan_Disbursement_Date { get; set; }
        public int Mode_of_Disbursement { get; set; }
        public string Affidavit___Item_1_Details { get; set; }
        public decimal Affidavit___Estimated_Value_1 { get; set; }
        public string Affidavit___Item_2_Details { get; set; }
        public decimal Affidavit___Estimated_Value_2 { get; set; }
        public string Affidavit___Item_3_Details { get; set; }
        public decimal Affidavit___Estimated_Value_3 { get; set; }
        public string Affidavit___Item_4_Details { get; set; }
        public decimal Affidavit___Estimated_Value_4 { get; set; }
        public string Affidavit___Item_5_Details { get; set; }
        public decimal Affidavit___Estimated_Value_5 { get; set; }
        public string Magistrate_Name { get; set; }
        public System.DateTime Date_for_Affidavit { get; set; }
        public string Name_of_Chief__Assistant { get; set; }
        public byte Affidavit_Signed_ { get; set; }
        public System.DateTime Date_Approved { get; set; }
        public string Grace_Period { get; set; }
        public string Instalment_Period { get; set; }
        public decimal Repayment { get; set; }
        public byte Pays_Interest_During_GP { get; set; }
        public decimal Percent_Repayments { get; set; }
        public string Paying_Bank_Account_No { get; set; }
        public string No__Series { get; set; }
        public string Loan_Product_Type_Name { get; set; }
        public string Cheque_Number { get; set; }
        public string Doc_No_Used { get; set; }
        public string Batch_No_ { get; set; }
        public byte Edit_Interest_Rate { get; set; }
        public byte Posted { get; set; }
        public string Product_Code { get; set; }
        public string Field_Office { get; set; }
        public string Dimension { get; set; }
        public decimal Amount_Disbursed { get; set; }
        public byte Fully_Disbursed { get; set; }
        public decimal New_Interest_Rate { get; set; }
        public int New_No__of_Instalment { get; set; }
        public string New_Grace_Period { get; set; }
        public string New_Regular_Instalment { get; set; }
        public decimal Loan_Balance_at_Rescheduling { get; set; }
        public byte Loan_Reschedule { get; set; }
        public System.DateTime Date_Rescheduled { get; set; }
        public string Reschedule_by { get; set; }
        public decimal Flat_Rate_Principal { get; set; }
        public decimal Flat_rate_Interest { get; set; }
        public int Interest_Calculation_Method { get; set; }
        public byte Edit_Interest_Calculation_Meth { get; set; }
        public decimal Balance_BF { get; set; }
        public System.DateTime Cheque_Date { get; set; }
        public decimal Loan_to_Share_Ratio { get; set; }
        public decimal Shares_Balance { get; set; }
        public int Max__Installments { get; set; }
        public decimal Max__Loan_Amount { get; set; }
        public int Loan_Cycle { get; set; }
        public int Repayment_Method { get; set; }
        public int Grace_Period___Principle__M_ { get; set; }
        public int Grace_Period___Interest__M_ { get; set; }
        public string Adjustment { get; set; }
        public string Payment_Due_Date { get; set; }
        public int Tranche_Number { get; set; }
        public decimal Amount_Of_Tranche { get; set; }
        public decimal Total_Disbursment_to_Date { get; set; }
        public byte Copy_of_ID { get; set; }
        public byte Contract { get; set; }
        public byte Payslip { get; set; }
        public decimal Contractual_Shares { get; set; }
        public int Appraisal_Status { get; set; }
        public string Global_Dimension_1_Code { get; set; }
        public System.DateTime Repayment_Start_Date { get; set; }
        public int Installment_Including_Grace { get; set; }
        public decimal Repayments_BF { get; set; }
        public string Account_No { get; set; }
        public string BOSA_No { get; set; }
        public string Staff_No { get; set; }
        public decimal BOSA_Loan_Amount { get; set; }
        public byte Loan_Received { get; set; }
        public string Cheque_No_ { get; set; }
        public decimal Personal_Loan_Off_set { get; set; }
        public string Old_Account_No_ { get; set; }
        public decimal Loan_Principle_Repayment { get; set; }
        public decimal Loan_Interest_Repayment { get; set; }
        public string Contra_Account { get; set; }
        public string Transacting_Branch { get; set; }
        public int Source { get; set; }
        public decimal Net_Income { get; set; }
        public byte Shares_Boosted { get; set; }
        public decimal Basic_Pay { get; set; }
        public decimal House_Allowance { get; set; }
        public decimal Other_Allowance { get; set; }
        public decimal Total_Deductions { get; set; }
        public decimal Cleared_Effects { get; set; }
        public string Remarks { get; set; }
        public byte Advice { get; set; }
        public byte Bridging_Loan_Posted { get; set; }
        public string BOSA_Loan_No_ { get; set; }
        public decimal Previous_Repayment { get; set; }
        public byte No_Loan_in_MB { get; set; }
        public decimal Recovered_Balance { get; set; }
        public byte Recon_Issue { get; set; }
        public string Loan_Purpose { get; set; }
        public byte Reconciled { get; set; }
        public decimal Appeal_Amount { get; set; }
        public byte Appeal_Posted { get; set; }
        public decimal Project_Amount { get; set; }
        public string Project_Account_No { get; set; }
        public decimal Discounted_Amount { get; set; }
        public decimal Transport_Allowance { get; set; }
        public decimal Mileage_Allowance { get; set; }
        public byte System_Created { get; set; }
        public decimal Boosting_Commision { get; set; }
        public decimal Voluntary_Deductions { get; set; }
        public byte C4___Bridging { get; set; }
        public int No__Of_Guarantors_FOSA { get; set; }
        public byte Defaulted { get; set; }
        public System.DateTime Bridging_Posting_Date { get; set; }
        public decimal Commitements_Offset { get; set; }
        public int Gender { get; set; }
        public string Captured_By { get; set; }
        public string Branch_Code { get; set; }
        public byte Recovered_From_Guarantor { get; set; }
        public decimal Guarantor_Amount { get; set; }
        public byte External_EFT { get; set; }
        public string Defaulter_Overide_Reasons { get; set; }
        public byte Defaulter_Overide { get; set; }
        public decimal Other_Benefits { get; set; }
        public string Recovered_Loan { get; set; }
        public System.DateTime C1st_Notice { get; set; }
        public System.DateTime C2nd_Notice { get; set; }
        public System.DateTime Final_Notice { get; set; }
        public System.DateTime Last_Advice_Date { get; set; }
        public int Advice_Type { get; set; }
        public decimal Compound_Balance { get; set; }
        public decimal Repayment_Rate { get; set; }
        public decimal Exp_Repay { get; set; }
        public string ID_NO { get; set; }
        public decimal RAmount { get; set; }
        public string Employer_Code { get; set; }
        public byte Lst_LN1 { get; set; }
        public byte Lst_LN2 { get; set; }
        public string Last_loan { get; set; }
        public int Loans_Category { get; set; }
        public int Loans_Category_SASRA { get; set; }
        public string Bela_Branch { get; set; }
        public decimal Net_Amount { get; set; }
        public string Bank_code { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Branch { get; set; }
        public byte Defaulter { get; set; }
        public string DefaulterInfo { get; set; }
        public decimal Total_Earnings_Salary_ { get; set; }
        public decimal Total_Deductions_Salary_ { get; set; }
        public decimal Share_Purchase { get; set; }
        public string Product_Currency_Code { get; set; }
        public decimal Amount_Disburse { get; set; }
        public int Appln__between_Currencies { get; set; }
        public System.DateTime Expected_Date_of_Completion { get; set; }
        public int Recovery_Mode { get; set; }
        public int Repayment_Frequency { get; set; }
        public int Approval_Status { get; set; }
        public string Old_Vendor_No { get; set; }
        public decimal Insurance_0_25 { get; set; }
        public decimal Total_loan_Outstanding { get; set; }
        public decimal Monthly_Shares_Cont { get; set; }
        public decimal Insurance_On_Shares { get; set; }
        public decimal Net_Payment_to_FOSA { get; set; }
        public byte Processed_Payment { get; set; }
        public System.DateTime Date_payment_Processed { get; set; }
        public decimal Attached_Amount { get; set; }
        public decimal PenaltyAttached { get; set; }
        public decimal InDueAttached { get; set; }
        public byte Attached { get; set; }
        public System.DateTime Advice_Date { get; set; }
        public System.DateTime Attachement_Date { get; set; }
        public decimal Jaza_Deposits { get; set; }
        public decimal Member_Deposits { get; set; }
        public decimal Levy_On_Jaza_Deposits { get; set; }
        public decimal Min_Deposit_As_Per_Tier { get; set; }
        public byte Bridged { get; set; }
        public decimal Deposit_Reinstatement { get; set; }
        public byte Member_Found { get; set; }
        public decimal Recommended_Amount { get; set; }
        public decimal Previous_Years_Dividend { get; set; }
        public byte partially_Bridged { get; set; }
        public decimal BOSA_Deposits { get; set; }
        public byte Loan_No_Found { get; set; }
        public string Checked_By { get; set; }
        public string Approved_By { get; set; }
        public int New_Repayment_Period { get; set; }
        public string Rejected_By { get; set; }
        public string Approval_remarks { get; set; }
        public decimal Loan_Disbursed_Amount { get; set; }
        public decimal Bank_Bridge_Amount { get; set; }
        public decimal Approved_Repayment { get; set; }
        public decimal Original_Approved_Amount { get; set; }
        public byte Original_Approved_Updated { get; set; }
        public decimal Interest_Upfront_Amount { get; set; }
        public decimal Loan_Processing_Fee { get; set; }
        public decimal Loan_Appraisal_Fee { get; set; }
        public decimal Loan_Insurance { get; set; }
        public byte Received_Copy_Of_ID { get; set; }
        public byte Received_Payslip_Bank_Statemen { get; set; }
        public byte C1st_Time_Loanee { get; set; }
        public decimal Adjted_Repayment { get; set; }
        public int Member_Category { get; set; }
        public decimal Shares_to_Boost { get; set; }
        public decimal Hisa_Allocation { get; set; }
        public decimal Hisa_Commission { get; set; }
        public decimal Hisa_Boosting_Commission { get; set; }
        public decimal Share_Capital_Due { get; set; }
        public decimal IntersetInArreas { get; set; }
        public decimal Upfronts { get; set; }
        public byte Loan_Calc__Offset_Loan { get; set; }
        public decimal Loan_Transfer_Fee { get; set; }
        public decimal Loan_SMS_Fee { get; set; }
        public decimal Penalty { get; set; }
        public decimal Basic_Pay_H { get; set; }
        public decimal Medical_AllowanceH { get; set; }
        public decimal House_AllowanceH { get; set; }
        public decimal Staff_Assement { get; set; }
        public decimal Pension { get; set; }
        public decimal Medical_Insurance { get; set; }
        public decimal Life_Insurance { get; set; }
        public decimal Other_Liabilities { get; set; }
        public decimal Transport_Bus_Fare { get; set; }
        public decimal Other_Income { get; set; }
        public decimal Pension_Scheme { get; set; }
        public decimal Other_Non_Taxable { get; set; }
        public decimal Monthly_Contribution { get; set; }
        public decimal Sacco_Deductions { get; set; }
        public decimal Other_Tax_Relief { get; set; }
        public decimal NHIF { get; set; }
        public decimal NSSF { get; set; }
        public decimal PAYE { get; set; }
        public decimal Risk_MGT { get; set; }
        public decimal Other_Loans_Repayments { get; set; }
        public byte Staff { get; set; }
        public byte Disabled { get; set; }
        public decimal Staff_Union_Contribution { get; set; }
        public decimal Non_Payroll_Payments { get; set; }
        public decimal Gross_Pay { get; set; }
        public decimal Total_DeductionsH { get; set; }
        public decimal Utilizable_Amount { get; set; }
        public decimal Net_Utilizable_Amount { get; set; }
        public decimal Net_take_Home { get; set; }
        public byte Signature { get; set; }
        public string Witnessed_By { get; set; }
        public string Witness_Name { get; set; }
        public byte Received_Copies_of_Payslip { get; set; }
        public decimal Interest_In_Arrears { get; set; }
        public byte Private_Member { get; set; }
        public decimal Loan_Processing { get; set; }
        public decimal Total_Topup_Amount { get; set; }
        public decimal Loan__Cash_Cleared { get; set; }
        public decimal Loan_Cash_Clearance_fee { get; set; }
        public System.DateTime Loan_Last_Pay_date_2009Nav { get; set; }
        public string Loans_Referee_1 { get; set; }
        public string Loans_Referee_1_Name { get; set; }
        public string Loans_Referee_2 { get; set; }
        public string Loans_Referee_2_Name { get; set; }
        public string Loans_Referee_1_Relationship { get; set; }
        public string Loans_Referee_2_Relationship { get; set; }
        public string Loans_Referee_1_Mobile_No_ { get; set; }
        public string Loans_Referee_2_Mobile_No_ { get; set; }
        public string Loans_Referee_1_Address { get; set; }
        public string Loans_Referee_2_Address { get; set; }
        public string Loans_Referee_1_Physical_Addre { get; set; }
        public string Loans_Referee_2_Physical_Addre { get; set; }
        public string Loan_to_Appeal { get; set; }
        public decimal Loan_to_Appeal_Approved_Amount { get; set; }
        public System.DateTime Loan_to_Appeal_issued_Date { get; set; }
        public byte Loan_Appeal { get; set; }
        public string Disbursed_By { get; set; }
        public int Member_Account_Category { get; set; }
        public byte Member_Not_Found { get; set; }
        public string Loan_to_Reschedule { get; set; }
        public byte Rescheduled { get; set; }
        public System.DateTime Loan_Rescheduled_Date { get; set; }
        public string Loan_Rescheduled_By { get; set; }
        public string Reason_For_Loan_Reschedule { get; set; }
        public byte Loan_Under_Debt_Collection { get; set; }
        public string Loan_Debt_Collector { get; set; }
        public decimal Loan_Debt_Collector_Interest__ { get; set; }
        public System.DateTime Debt_Collection_date_Assigned { get; set; }
        public string Debt_Collector_Name { get; set; }
        public int Disburesment_Type { get; set; }
        public decimal Amount_to_Disburse { get; set; }
        public string Member_Cell_Group { get; set; }
        public string Member_Cell_Group_Name { get; set; }
        public string Mobile_No { get; set; }
        public string Recovery_Option { get; set; }
        public int Loan_Recovery_Priority { get; set; }
        public byte Found { get; set; }
        public System.DateTime Last_day { get; set; }
        public byte Loan_Dev { get; set; }
        public byte Reversed { get; set; }
        public byte Dontnotcapitalize { get; set; }
        public decimal Amount_In_Arrears { get; set; }
        public byte partial { get; set; }
        public decimal Net_Loan_Disbursed { get; set; }
        public int Payroll_CodeB { get; set; }
        public System.DateTime Appeal_Date { get; set; }
        public byte Appeal_Loan { get; set; }
        public byte Extra_To_Loan { get; set; }
        public decimal Balance_After { get; set; }
        public decimal Original_Top_Up { get; set; }
        public byte Topped_Up { get; set; }
        public byte Exempt_Charges { get; set; }
        public int New_Installments { get; set; }
        public byte Diaspora_ { get; set; }
        public byte Partial_Top_Up { get; set; }

        //Calculated variables

        United_Women_Sacco_Ltd_Member_Ledger_Entry mle = new United_Women_Sacco_Ltd_Member_Ledger_Entry();

    }
}
