//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitedWomenMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class United_Women_Sacco_Ltd_Members_Nominee
    {
        public byte[] timestamp { get; set; }
        public string Account_No { get; set; }
        public string Name { get; set; }
        public string Relationship { get; set; }
        public byte Beneficiary { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string ID_No_ { get; set; }
        public decimal C_Allocation { get; set; }
        public byte New_Upload { get; set; }
        public decimal Maximun_Allocation__ { get; set; }
        public string NOK_Residence { get; set; }
        public string Member_No_ { get; set; }
    }
}
