//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitedWomenMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class United_Women_Sacco_Ltd_Member_Account_Signatories
    {
        public byte[] timestamp { get; set; }
        public string Account_No { get; set; }
        public string Names { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Staff_Payroll { get; set; }
        public string ID_No_ { get; set; }
        public byte Signatory { get; set; }
        public byte Must_Sign { get; set; }
        public byte Must_be_Present { get; set; }
        public byte[] Picture { get; set; }
        public byte[] Signature { get; set; }
        public System.DateTime Expiry_Date { get; set; }
        public string Sections_Code { get; set; }
        public string Company_Code { get; set; }
        public string BOSA_No_ { get; set; }
        public string Email_Address { get; set; }
        public string Designation { get; set; }
    }
}
